### ISSUE TITLE
Question about Fresnel propagation operator in psf_layer_coded_aperture_limited_filters.py

### ISSUE THREAD

**Issue by sihan-shao** [jorgebaccauis/Shift-Variant-System#1]
Hi! It's impressive work. Recently I read the code for this work and I met some problems about Fresnel propagation operator.

> In psf_layer_coded_aperture_limited_filters.py  **line 381-384**

```python
out_field1 = propagation(output_field_circ, self.sample_interval, wave_lengths, self.distance_code) 
out_field1 = K.multiply(out_field1, maskShif)
out_field1 = propagation_back(out_field1, self.sample_interval, wave_lengths, self.distance_code)
out_field1 = propagation(out_field1, self.sample_interval, wave_lengths, self.distance)
```

The wave field incident on the diffractive optical element and then is propagated a distance z1 before the CCA using the Fresnel propagation operator. 

```python
out_field1 = propagation(output_field_circ, self.sample_interval, wave_lengths, self.distance_code) 
```

The wave field is modulated by CCA
```python
out_field1 = K.multiply(out_field1, maskShif)
```

My question is **Why do we need to _propagation_back_ the modulated wave field and reuse the Fresnel diffraction formula instead of directly using it in the modulated wave field?**

```python
out_field1 = propagation_back(out_field1, self.sample_interval, wave_lengths, self.distance_code)
out_field1 = propagation(out_field1, self.sample_interval, wave_lengths, self.distance)
```

**Comment by jorgebaccauis** [comment]
In our system, we assume that CA only applied intensity modulation. Therefore, a possible implementation is multiplied by the mask and continues the propagation up to the distance ( self.distance-self.distance_code), in this case, we need to continue with the propagation which requires changes in the discretization. In sted of doing that, we implement a propagation back to emulated the coded field and then propagate up to the sensor, which is the same that continues the propagation.
